In [1]:
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import SCORERS

In [2]:
df=pd.read_csv("./Advertising.csv")
df.head()
X=df.drop("sales",axis=1)
y=df["sales"]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [4]:
scaler_model=StandardScaler()
scaler_model.fit(X_train)
X_train=scaler_model.transform(X_train)
X_test=scaler_model.transform(X_test)

In [13]:
elastic_model=ElasticNet()
params={"alpha":[0.1,0.2,0.5,1],"l1_ratio":[0.1,0.2,0.5,1]}
grid_model=GridSearchCV(estimator=elastic_model,scoring="neg_mean_absolute_error",
                        cv=5,param_grid=params)

In [14]:
grid_model.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 0.2, 0.5, 1],
                         'l1_ratio': [0.1, 0.2, 0.5, 1]},
             scoring='neg_mean_absolute_error')

In [15]:
grid_model.best_score_

-1.285649424311538

In [8]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 0.1}

In [9]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=0.1)

In [10]:
results=grid_model.cv_results_
df=pd.DataFrame(results)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002843,0.001030,0.002883,0.003801,0.1,0.1,"{'alpha': 0.1, 'l1_ratio': 0.1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,0.001871,0.000661,0.001025,0.000245,0.1,0.2,"{'alpha': 0.1, 'l1_ratio': 0.2}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,0.001848,0.000693,0.000977,0.000238,0.1,0.5,"{'alpha': 0.1, 'l1_ratio': 0.5}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,0.001550,0.000247,0.001097,0.000561,0.1,1,"{'alpha': 0.1, 'l1_ratio': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,0.001619,0.000319,0.000868,0.000137,0.2,0.1,"{'alpha': 0.2, 'l1_ratio': 0.1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.001540,0.000181,0.001082,0.000378,0.2,0.2,"{'alpha': 0.2, 'l1_ratio': 0.2}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
6,0.001425,0.000156,0.000995,0.000139,0.2,0.5,"{'alpha': 0.2, 'l1_ratio': 0.5}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,0.001374,0.000123,0.000955,0.000222,0.2,1,"{'alpha': 0.2, 'l1_ratio': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
8,0.001391,0.000286,0.000905,0.000103,0.5,0.1,"{'alpha': 0.5, 'l1_ratio': 0.1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
9,0.002035,0.000796,0.000855,0.000084,0.5,0.2,"{'alpha': 0.5, 'l1_ratio': 0.2}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
10,0.001496,0.000279,0.000920,0.000251,0.5,0.5,"{'alpha': 0.5, 'l1_ratio': 0.5}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
11,0.001588,0.000245,0.000949,0.000326,0.5,1,"{'alpha': 0.5, 'l1_ratio': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
12,0.001901,0.000592,0.001251,0.000320,1,0.1,"{'alpha': 1, 'l1_ratio': 0.1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.002069,0.000324,0.002077,0.000414,1,0.2,"{'alpha': 1, 'l1_ratio': 0.2}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.002540,0.000876,0.001256,0.000810,1,0.5,"{'alpha': 1, 'l1_ratio': 0.5}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.002632,0.001242,0.001625,0.001061,1,1,"{'alpha': 1, 'l1_ratio': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16

In [11]:
prediction=grid_model.predict(X_test)
prediction

array([16.25799047, 20.29215346, 21.00707154, 10.82871394, 21.23827558,
       13.17852828, 20.38248512,  7.99821586, 13.72161045, 15.08651368,
        9.31889617,  7.33199919, 14.65901578,  9.17350099, 10.15498861,
       12.43570331,  9.14450812, 16.04663468, 10.59318228, 18.37993024])

In [12]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])